AWSTemplateFormatVersion: '2010-09-09'
Resources:
    NestedStack:
      Type: 'AWS::CloudFormation::Stack'
      Properties: 
          TemplateURL: 'https://notearshpc-quickstart.s3.amazonaws.com/0.2.2/cfn.yaml'
          Parameters: 
            OperatingSystem: alinux2
            EnableBudget: false
            CreateServiceLinkedRoles: false
